channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - six
  - tqdm
  - future
  - numpy
  - matplotlib
  - networkx
  - dataclasses
  - pytest
  - jupyterlab
  - nbformat

  - pip
  - pip:
        - nbmerge
        - brine