channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - six
  - tqdm
  - future
  - numpy
  - matplotlib
  - networkx
  - dataclasses
  - pytest
  - jupyterlab
  - nbformat
  - pygraphviz

  - pip
  - pip:
        - nbmerge
        - brine
        - jupyterlab-link-share # https://discourse.jupyter.org/t/collaborating-on-one-binder-instance/407/8